### ISSUE TITLE
Чертёж общего вида

### ISSUE THREAD

**Issue by ak-git** [Tatyanka/N1#1]
Ссылка на приборные корпуса http://www.gainta.ru/products/bodies/files/Gainta_Catalogue.pdf

**Comment by ak-git** [comment]
http://www.okw.ru/Binary/Okw/okw_1ru.pdf

**Comment by ak-git** [comment]
Вот образцово-показательный корпус http://www.apple.com/ru/ipod-shuffle/
И ещё сайт по корпусам http://www.korpusa.ru/

http://www.korpusa.ru/files/cases/efo_case/238721_minitec.pdf
http://www.korpusa.ru/files/cases/efo_case/437628_NoVoTronic_GB.pdf
http://www.korpusa.ru/files/cases/efo_case/839728_1455.pdf

**Comment by Tatyanka** [comment]
На minitec я уже засматривалась, они красивые такие, но там батарейного отсека нет. Он же мне нужен, я правильно понимаю? И я начала чертить вот этот: 
http://www.okw.com/OPD-WebSite/A9052117/SOFT-CASE-L/viewProduct.okw

**Comment by ak-git** [comment]
Батарейки нужны. Или аккумулятор встроенный, но тогда разъём для подзарадки должен быть.
Вот тут есть батарейный отсек http://www.tekoportal.com/en/prodotti/famiglia/AL/serie/140
Даже с чертежами уже в AutoCAD (DWG)

Полный комплект http://www.tekoportal.com

**Comment by ak-git** [comment]
Ещё лучше нашёл корпуса
http://www.rolec.de/mobile_control_enclosures_ru,115403.html
http://www.rolec.de/download/15-handCASE_RUS.pdf
http://www.rolec.de/download/16-mobilCASE_RUS.pdf

**Comment by ak-git** [comment]
А чертёж электродов это не чертёж общего вида!

**Comment by Tatyanka** [comment]
Нуу..это его часть
